In [2]:
import tensorflow as tf

### Tensor Basics
tf.constant(value, dtype, shape, name)

In [3]:
# Rank-0 or Scalar tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
# Rank-1 or Vector tensor
rank_1_tensor = tf.constant([2,3,4])
print(rank_1_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [10]:
rank_1_tensor.shape

TensorShape([3])

In [6]:
# Rank-2 or Matrix tensor
rank_2_tensor = tf.constant([[2,3,4], [4,5,6]])
print(rank_2_tensor)

tf.Tensor(
[[2 3 4]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
# Rank-3 Tensor
rank_3_tensor = tf.constant([[[2,3,4], [4,5,6]], [[6,7,8],[5,6,7]]])
print(rank_3_tensor)

tf.Tensor(
[[[2 3 4]
  [4 5 6]]

 [[6 7 8]
  [5 6 7]]], shape=(2, 2, 3), dtype=int32)


### Conversion
You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:

In [11]:
tensor = tf.constant([[2,3,4,5],[3,4,5,6]])

In [16]:
# Tensor to numpy array
import numpy as np
numpy = np.array(tensor)
numpy

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [17]:
numpy = tensor.numpy()
numpy

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [20]:
# Numpy to Tensor
np_array = np.array([[2,3,4],[2,3,4]])
tf_tensor = tf.convert_to_tensor(np_array)
tf_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [2, 3, 4]])>

### Tensor operations

In [30]:
a = tf.constant([[1,2],
                 [2,3]])
b = tf.constant([[3,4],
                 [5,6]])

In [32]:
print(tf.add(a,b),"\n")
print(tf.multiply(a,b),"\n")
print(tf.matmul(a,b),"\n")

tf.Tensor(
[[4 6]
 [7 9]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  8]
 [10 18]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[13 16]
 [21 26]], shape=(2, 2), dtype=int32) 



In [34]:
print(a + b, "\n") # Element-wise addition
print(a * b, "\n") # Element-wise multiplication
print(a @ b, "\n") # Matrix multiplication

tf.Tensor(
[[4 6]
 [7 9]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  8]
 [10 18]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[13 16]
 [21 26]], shape=(2, 2), dtype=int32) 



In [46]:
# Basics usecase
x = tf.constant([[2, 6, 4], 
                 [11, 4, 5]], dtype=float)

print(tf.reduce_max(x)) # Find the largest value
print(tf.math.argmax(x)) # find the index of max value
print(tf.nn.softmax(x)) # Compute softmax

tf.Tensor(11.0, shape=(), dtype=float32)
tf.Tensor([1 0 1], shape=(3,), dtype=int64)
tf.Tensor(
[[1.5876239e-02 8.6681336e-01 1.1731043e-01]
 [9.9662089e-01 9.0880063e-04 2.4703762e-03]], shape=(2, 3), dtype=float32)


### Tensor Shapes
* Shape: The length (number of elements) of each of the axes of a tensor.
* Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor, the product of the shape vector's elements.

In [4]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
# print(rank_4_tensor)

In [7]:
rank_4_tensor.dtype

tf.float32

In [9]:
rank_4_tensor.ndim

4

In [10]:
rank_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [11]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [12]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

### Index

In [23]:
x = tf.constant([2,3,4,5])
y = tf.constant([[2,3,4],[6,7,8]])

In [21]:
x[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [22]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [27]:
y[:1,1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>