In [1]:
import torch
import tensorflow as tf
import numpy as np

## Expending dimensions in torch

In [2]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [3]:
# expending one dimension
t.unsqueeze(dim=0)

tensor([[1, 2, 3]])

In [4]:
t.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3]])

In [35]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [36]:
torch.cat((t1,t2,t3), dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [37]:
torch.stack((t1,t2,t3), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [38]:
torch.cat((
    t1.unsqueeze(0),
    t2.unsqueeze(0),
    t3.unsqueeze(0)
), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [39]:
torch.stack((t1,t2,t3), dim=1)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

## using tensorflow

In [17]:
t1 = tf.constant([1,2,3])
t2 = tf.constant([1,2,3])
t3 = tf.constant([1,2,3])

In [19]:
tf.concat((t1,t2,t3), axis=0)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 1, 2, 3, 1, 2, 3])>

In [20]:
tf.stack((t1,t2,t3), axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [25]:
tf.concat((
    tf.expand_dims(t1, 0),
    tf.expand_dims(t2, 0),
    tf.expand_dims(t3, 0)
), axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

## using numpy

In [26]:
t1 = np.array([1,2,3])
t2 = np.array([1,2,3])
t3 = np.array([1,2,3])

In [30]:
np.concatenate((t1,t2,t3), axis=0)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
np.stack((t1,t2,t3), axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
np.concatenate((
    np.expand_dims(t1, 0),
    np.expand_dims(t2, 0),
    np.expand_dims(t3, 0)
),axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
??np.stack

Signature:       np.stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')
Call signature:  np.stack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function stack at 0x0000024E79501120>
File:            c:\users\saraw\appdata\local\programs\python\python312\lib\site-packages\numpy\core\shape_base.py
Source:         
@array_function_dispatch(_stack_dispatcher)
def stack(arrays, axis=0, out=None, *, dtype=None, casting="same_kind"):
    """
    Join a sequence of arrays along a new axis.

    The ``axis`` parameter specifies the index of the new axis in the
    dimensions of the result. For example, if ``axis=0`` it will be the first
    dimension and if ``axis=-1`` it will be the last dimension.

    .. versionadded:: 1.10.0

    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.

    axis : int, optional
        The axis in the result array along which the input arrays are stacked.

    o